AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for voting automation'

Resources:
  VotingBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'voting-screenshots-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldScreenshots
            Status: Enabled
            ExpirationInDays: 7

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref VotingBucket
